# Generated by Django 4.2.3 on 2024-02-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default=2, upload_to='users/'),
            preserve_default=False,
        ),
    ]
