# Generated by Django 4.2.3 on 2024-02-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_magazin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foydalanuvchilar', models.IntegerField()),
                ('nomi', models.CharField(max_length=100)),
            ],
        ),
    ]
