# Generated by Django 4.2.3 on 2024-02-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_follow_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Get_in_touch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_raqam', models.IntegerField()),
                ('lakatsiya', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
