# Generated by Django 4.2.3 on 2024-02-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_get_in_touch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telfon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
    ]
